### PR TITLE
Optimize source code

### PR DESCRIPTION
**Pull request by dinhthuanbk88**
A small change increase the performance up to 30% (tested)

### CODE REVIEW

**Comment by bitdust** [comment]
test on my computer
(E3-1230V3 windows8.1x64 VS2013)

osqzss:master

> Time into run = 300.0
> Done!
> Process time = 77.5 [sec]

dinhthuanbk88:master

> Time into run = 300.0
> Done!
> Process time = 45.2 [sec]

**Comment by IvanKor** [comment]
//i_acc += (ip + 50) / 100;     //Process time = 30.9 [sec]
					//q_acc += (qp + 50) / 100;
					i_acc += ip >> 7;		//Process time = 22.6 [sec]
					q_acc += qp >> 7;

**Comment by bitdust** [comment]
@IvanKor 
cool~
those 2 lines are so hot
image

**Comment by osqzss** [comment]
Thank you for a simple and effective modification idea. I put the changes of dinhthuanbk88 and IvanKor together and merged them into the current master.

**Pull request closed without merging**
