### PR TITLE
Support realtime through Gnuradio.

### PR DESCRIPTION
**Pull request by gym487**
Using the "TCP Source" in Gnuradio.

### CODE REVIEW

**Comment by osqzss** [comment]
Thank you for adding Gnuradio support. But I would like to keep my code a simple baseband generator and hesitate to merge any platform or target dependent features to the master branch.

**Comment by gym487** [comment]
Thanks for reply.

In fact I just added a feature that outputting I/Q data stream through TCP real-timely (So that the Gnuradio module "TCP Sink" or other programs could receive I/Q data real-timely).

And the "tcp.grc" is a simple Gnuradio demo which could transmit  the I/Q data received by "TCP Sink".

Could we merge it as a extra module based on Gnuradio  just like the "gps-sdr-sim-uhd.py"?

**Comment by osqzss** [comment]
I'm not very familiar with socket programming, but I think your TCP related code is not compatible with Windows environment. If there's any Windows SDR tool accepting "TCP source" like Gnuradio, it could be worth adding a TCP streaming feature supporting both Windows and Linux. I'm sorry I've never been a Linux person.

**Comment by gym487** [comment]
Thanks. I see.

**Comment by MAVProxyUser** [comment]
I really wish you were not so adverse to people helping with this code base @osqzss !!!! You seem to shut down good improvements on the regular, resulting in a fragmented set of forks of your code all over the place :/

**Pull request closed without merging**
